swagger: "2.0"
info:
  description: "Documentação básica para utilização da api em desenvolvimento da nova versão do BackOffice. Desenvolvido usando o framework PHP Hyperf (https://hyperf.wiki/2.2/#/en/)"
  version: "3.0.0"
  title: "BackOffice API"
  contact:
    email: "rafael.oliveira@onfly.com.br"
tags:
- name: "auth"
  description: "Serviços de autenticação"
- name: "user"
  description: "Serviços de usuários"
- name: "permissions"
  description: "Serviços de usuários"  
schemes: 
- "http"
paths:
  "/auth/":
    post:
      tags:
      - "auth"
      summary: "Executa a autenticação do usuário"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "Dados de autenticação do usuário"
        required: true
        schema:
          $ref: "#/definitions/Auth"          
      responses:
        "200":
          description: "autenticado com sucesso"
          schema:
            $ref: "#/definitions/Authenticated"
        "422":
          description: "Os dados enviados são inválidos"
        "400":
          description: "Dados de fornecidos estão incorretos"  
        "404":
          description: "Usuário não encontrado"  
        "500":
          description: "Internal Server Error"
    get:
      tags:
      - "auth"
      summary: "Obtem os dados do usuário logado"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"         
      responses:
        "200":
          description: "autenticado com sucesso"
          schema:
            $ref: '#/definitions/UserData'
        "422":
          description: "Os dados enviados são inválidos"
        "400":
          description: "Dados de fornecidos estão incorretos"  
        "404":
          description: "Usuário não encontrado"  
        "500":
          description: "Internal Server Error"      
  "/auth/refresh":
    get:
      tags:
      - "auth"
      summary: "Renova o token do usuário"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      responses:
        "200":
          description: "autenticado com sucesso"
          schema:
            $ref: "#/definitions/Authenticated"
        "400":
          description: "Token authentication does not pass"     
        "500":
          description: "Internal Server Error"
  "/auth/logout":
    get:
      tags:
      - "auth"
      summary: "Executa o logout do usuário"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      responses:
        "200":
          description: "Logout efetuado com sucesso"
          schema:
            $ref: "#/definitions/Logout"
        "500":
          description: "Internal Server Error" 
  "/user/":
    get:
      tags:
      - "user"
      summary: "Lista todos os usuários cadastrados"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      responses:
        "200":
          description: "Sucesso"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Os dados enviados são inválidos"    
        "500":
          description: "Internal Server Error"
    post:
      tags:
      - "user"
      summary: "Executa o cadastro de usuários"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "Dados de cadastro do usuário"
        required: true
        schema:
          $ref: "#/definitions/UserData"             
      responses:
        "200":
          description: "Usuário cadastrado com sucesso"
          schema:
            $ref: "#/definitions/User"
        "422":
          description: "Os dados enviados são inválidos"    
        "500":
          description: "Internal Server Error"           
  "/user/{Id}":
    put:
      tags:
      - "user"
      summary: "Atualiza os dados de usuários"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "Id"
        in: "path"
        description: "ID do usuário"
        required: true
        type: "integer"        
      - name: "body"
        in: "body"
        description: "Dados de cadastro do usuário"
        required: true
        schema:
          $ref: "#/definitions/Register"             
      responses:
        "200":
          description: "Usuário cadastrado com sucesso"
          schema:
            $ref: "#/definitions/User"
        "422":
          description: "Os dados enviados são inválidos"    
        "500":
          description: "Internal Server Error"           
    get:
      tags:
      - "user"
      summary: "Retorno usuário pelo ID"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "Id"
        in: "path"
        description: "ID do usuário"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Sucesso"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Os dados enviados são inválidos"    
        "500":
          description: "Internal Server Error" 
    delete:
      tags:
      - "user"
      summary: "Exclui um usuário"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "Id"
        in: "path"
        description: "ID do usuário"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Sucesso"
        "400":
          description: "Os dados enviados são inválidos"    
        "500":
          description: "Internal Server Error"
  "/user/permission/add":
    patch:
      tags:
      - "user"
      summary: "Atribui permissões a usuário"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "Dados de autenticação do usuário"
        required: true
        schema:
          $ref: "#/definitions/PermissionsAssign"         
      responses:
        "200":
          description: "Sucesso"
        "500":
          description: "Internal Server Error"
  "/user/permission/remove":
    patch:
      tags:
      - "user"
      summary: "Remove permissões a usuário"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "Dados de autenticação do usuário"
        required: true
        schema:
          $ref: "#/definitions/PermissionsAssign"         
      responses:
        "200":
          description: "Sucesso"
        "500":
          description: "Internal Server Error"           
  "/permission/":
    get:
      tags:
      - "permissions"
      summary: "Lista Permissões cadastradas"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      responses:
        "200":
          description: "Sucesso"
          schema:
            $ref: "#/definitions/Permissions"
        "500":
          description: "Internal Server Error"
    post:
      tags:
      - "permissions"
      summary: "Adiciona novas permissões"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "Dados de autenticação do usuário"
        required: true
        schema:
          $ref: "#/definitions/PermissionsStore"        
      responses:
        "200":
          description: "Sucesso"
          schema:
            $ref: "#/definitions/Permissions"
        "500":
          description: "Internal Server Error"
  "/permission/{Id}":
    put:
      tags:
      - "permissions"
      summary: "Edita permissões"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "Id"
        in: "path"
        description: "ID do da permissão"
        required: true
        type: "integer"        
      - name: "body"
        in: "body"
        description: "Dados de autenticação do usuário"
        required: true
        schema:
          $ref: "#/definitions/PermissionsStore"        
      responses:
        "200":
          description: "Sucesso"
          schema:
            $ref: "#/definitions/Permissions"
        "500":
          description: "Internal Server Error"  
    delete:
      tags:
      - "permissions"
      summary: "Edita permissões"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de autorização do usuário"
        required: true
        type: "string"
      - name: "Id"
        in: "path"
        description: "ID do da permissão"
        required: true
        type: "integer"        
      responses:
        "200":
          description: "Sucesso"
        "500":
          description: "Internal Server Error"
definitions:          
  Auth:
    type: "object"
    properties:
      email:
        type: "string"
        example: "teste@teste.com"
      password:
        type: "string"
        example: "123456"
  Authenticated:
    type: "object"
    properties:
      message:
        type: "string"
        example: "success"
      data:
        type: "object"
        $ref: "#/definitions/Token"
  Token:
    type: "object"
    properties:
      token:
        type: "string"
        example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUz..."
      exp:
        type: "integer"
        format: "int64"
        example: 7200
  Logout:
    type: "object"
    properties:
      message:
        type: "string"
        example: "Logout efetuado com sucesso"
  User:
    type: "object"
    properties:
      data:
        type: "object"
        $ref: "#/definitions/UserData"
  UserData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1    
      name:
        type: "string"
        example: "Angelina Jolie da Silva"        
      email:
        type: "string"
        example: "angelina.jolie@teste.com"
      is_active:
        type: "boolean"
        example: "true" 
      is_admin:
        type: "boolean"
        example: "false"
      permission:
        type: array
        items:
          type: "string"
          example: "cadastro-acordos-automovel"
  Permissions:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1    
      segment:
        type: "string"
        example: "Acordos"
      name:
        type: "string"
        example: "Exclusão de acordos de automóvel"        
      flag:
        type: "string"
        example: "exclusao-acordos-automovel" 
      description:
        type: "string"
        example: "Descrição sobre esta permissão"
  PermissionsStore:
    type: "object"
    properties:
      segment:
        type: "string"
        example: "Acordos"
      name:
        type: "string"
        example: "Exclusão de acordos de automóvel"        
      flag:
        type: "string"
        example: "exclusao-acordos-automovel" 
      description:
        type: "string"
        example: "Descrição sobre esta permissão" 
  PermissionsAssign:
    type: "object"
    properties:
      user_id:
        type: "integer"
        example: 1
      permission_id:
        type: "integer"
        example: 5       
  Register:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Angelina Jolie da Silva"
      email:
        type: "string"
        example: "angelina.jolie@teste.com"
      password:
        type: "string"
        example: "123456"
      is_active:
        type: "boolean"
        example: "true" 
      is_admin:
        type: "boolean"
        example: "false"         